### ISSUE TITLE
Hamburger

### ISSUE THREAD

**Issue by oschl-git** [NeDDy3z/Traffair#1]
🍔

**Comment by NeDDy3z** [comment]
I'll report you to the police for stalking and public humiliation 😿
_PS: 🍔will be added to the game._

**Comment by NeDDy3z** [comment]
1:20 chance to spawn burgir in bonus content menu, happy? ugh..
<img width="1439" alt="img" src="https://github.com/NeDDy3z/Traffair/assets/79312101/607b75c7-5ef1-4c91-b0b9-dce983f67da7">
